services:
  db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: wucrypto
      POSTGRES_PASSWORD: wucrypto
      POSTGRES_DB: wucrypto
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
